import { useState } from 'react';
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { Button, Input } from './Components';

export default function Home() {
    const [ state, setState ] = useState();
  return (
    <div className={styles.container}>
      <Head>
        <title>Chat-io | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Input placeholder="username"></Input>
        <Input placeholder="password"></Input>
        <Button>Iniciar Sesion</Button>
        <Link href="/register">Registrarse</Link>
      </div>
    </div>
  )
}
