import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { Button, Input } from './Components';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chat-io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Input placeholder="username"></Input>
        <Input placeholder="password"></Input>
        <Input placeholder="email"></Input>
        <Button>Registrarse</Button>
        <Link href="/login">Iniciar Sesion</Link>
      </div>
    </div>
  )
}
